# Generated by Django 5.2 on 2025-05-02 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_foundationcourse_price_alter_module_price_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.module'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payme_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.tariff'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.foundationcourse'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('waiting', 'Waiting'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='created', max_length=20),
        ),
    ]
