# Generated by Django 5.2 on 2025-05-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_teacher_company_teacher_experience_teacher_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
