# Generated by Django 5.2 on 2025-05-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_teacher_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='photo',
        ),
    ]
