# Generated by Django 5.2 on 2025-05-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_remove_speciality_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='foundation',
        ),
        migrations.AddField(
            model_name='foundationcourse',
            name='videos',
            field=models.ManyToManyField(related_name='foundation_courses', to='education.video'),
        ),
    ]
