# Generated by Django 5.2 on 2025-05-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_remove_video_foundation_foundationcourse_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
