# Generated by Django 5.2 on 2025-05-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_tariff_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundationcourse',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
